This is makeindex, version 2.17 [TeX Live 2023] (kpathsea + Thai support).
Scanning style file ./hsrtreport_example.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file hsrtreport_example.acn....done (4 entries accepted, 0 rejected).
Sorting entries....done (10 comparisons).
Generating output file hsrtreport_example.acr....done (11 lines written, 0 warnings).
Output written in hsrtreport_example.acr.
Transcript written in hsrtreport_example.alg.
