[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "backend_simulator"
version = "0.0.0"
authors = [
  { name="Frederik Beimgraben", email="frederik@beimgraben.net" },
]
description = "Project to have less LaTeX when writing LaTeX"
# readme = "README.md"
requires-python = ">=3.13"
dependencies = ["pydantic", "marko"]

[project.optional-dependencies]
dev = ["pytest"]

[project.scripts]
main = "main:main"

[tool.setuptools.packages.find]
where = ["src"]

[tool.pyright]
extraPaths = ["src"]
