[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pylatex"
version = "0.1.0"
authors = [
  { name="Frederik Beimgraben", email="frederik@beimgraben.net" },
]
description = "Type-safe LaTeX document generation with Python"
# readme = "README.md"
requires-python = ">=3.13"
dependencies = ["pydantic", "marko"]

[project.optional-dependencies]
dev = ["pytest"]

[project.scripts]
build-pytex = "pytex.scripts.build_pytex:main"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
pytex_hsrtreport = ["Assets/**/*"]

[tool.pyright]
extraPaths = ["src"]
