from .library.builtins import (
    Bold,
    Emph,
    Href,
    Huge,
    HugeHuge,
    Italic,
    Large,
    LargeLarge,
    LargeLargeLarge,
    Newline,
    Paragraph,
    Relax,
    Section,
    Small,
    SmallCaps,
    Subparagraph,
    Subscript,
    Subsection,
    Subsubsection,
    Superscript,
    Texttt,
    Tiny,
    Underline,
)
from .library.document import Document
from .library.document_builtins import MakeTitle, NewPage, TableOfContents
from .library.environments import Enumerate, Environment, Item, Itemize, Quote, Verbatim
from .library.figures import (
    SVG,
    Figure,
    HLine,
    IncludeGraphics,
    Row,
    Table,
    Tabular,
    tabular,
)
from .library.glossaries import (
    Acronyms,
    AcronymEntry,
    Glossary,
    GlossaryEntry,
    MakeGlossaries,
    PrintGlossary,
    acr,
    acrfull,
    acrlong,
    gls,
    glspl,
)
from .library.inclusion import Include, IncludeTeX
from .library.listings import (
    Bash,
    C,
    Cpp,
    Html,
    InlineCode,
    Java,
    JavaScript,
    Json,
    LaTeXListing,
    Listing,
    LstDefineStyle,
    LstSet,
    Php,
    Python,
    Rust,
    Shell,
    Sql,
    TypeScript,
)
from .library.markdown import Markdown
from .library.math import (
    Align,
    AlignStar,
    DisplayMath,
    Equation,
    EquationStar,
    Gather,
    InlineMath,
)
from .library.references import (
    Cite,
    ColorBox,
    FBox,
    Footnote,
    Label,
    PageRef,
    Ref,
    TextColor,
    cite,
)
from .model.base_model import Package, TeX
from .model.group import Group
from .model.raw import Raw

__version__ = "0.1.0"

__all__ = [
    "__version__",
    # Core types
    "TeX",
    "Package",
    "Raw",
    "Group",
    # Document structure
    "Document",
    "MakeTitle",
    "TableOfContents",
    "NewPage",
    # Text formatting
    "Bold",
    "Italic",
    "Texttt",
    "Underline",
    "Emph",
    "SmallCaps",
    "Superscript",
    "Subscript",
    # Font sizes
    "Tiny",
    "Small",
    "Large",
    "LargeLarge",
    "LargeLargeLarge",
    "Huge",
    "HugeHuge",
    # Sections
    "Section",
    "Subsection",
    "Subsubsection",
    "Paragraph",
    "Subparagraph",
    # Links and utilities
    "Href",
    "Newline",
    "Relax",
    # Environments
    "Environment",
    "Item",
    "Itemize",
    "Enumerate",
    "Quote",
    "Verbatim",
    # Math
    "InlineMath",
    "DisplayMath",
    "Equation",
    "EquationStar",
    "Align",
    "AlignStar",
    "Gather",
    # Figures & tables
    "IncludeGraphics",
    "SVG",
    "Figure",
    "Table",
    "Tabular",
    "tabular",
    "Row",
    "HLine",
    # References, citations, footnotes
    "Label",
    "Ref",
    "PageRef",
    "Cite",
    "cite",
    "Footnote",
    # Colors & boxes
    "TextColor",
    "ColorBox",
    "FBox",
    # File inclusion
    "Include",
    "IncludeTeX",
    # Glossaries
    "Glossary",
    "GlossaryEntry",
    "Acronyms",
    "AcronymEntry",
    "MakeGlossaries",
    "PrintGlossary",
    "gls",
    "glspl",
    "acr",
    "acrlong",
    "acrfull",
    # Listings
    "Listing",
    "LstSet",
    "LstDefineStyle",
    "InlineCode",
    "Python",
    "JavaScript",
    "TypeScript",
    "Cpp",
    "C",
    "Java",
    "Shell",
    "Bash",
    "Sql",
    "Html",
    "Php",
    "Rust",
    "Json",
    "LaTeXListing",
    # Markdown
    "Markdown",
]
