from .library.biblatex import (
    AddBibResource,
    DeclareCiteCommand,
    DeclareFieldFormat,
    DeclareNameAlias,
    ExecuteBibliographyOptions,
    PrintBibliography,
)
from .library.builtins import (
    Apptocmd,
    AssignToks,
    AtBeginDocument,
    AtBeginEnvironment,
    AtEndDocument,
    AtEndEnvironment,
    BeginAccSupp,
    Bold,
    BuiltinPackages,
    Command,
    CounterWithin,
    CounterWithout,
    Crefname,
    DeclareRobustCommand,
    Def,
    Emph,
    GlobalDef,
    Href,
    Huge,
    HugeHuge,
    Hypersetup,
    Ifdefstring,
    IfFontExistsTF,
    Ifnum,
    IfUndefined,
    ImmediateWrite,
    Italic,
    Large,
    LargeLarge,
    LargeLargeLarge,
    Let,
    MakeAtLetter,
    NewCommand,
    NewCounter,
    NewEnvironment,
    Newline,
    NewLength,
    NewToks,
    Paragraph,
    Pretocmd,
    ProvideCommand,
    RegisterAssign,
    Relax,
    RenewCommand,
    Section,
    SetCounter,
    SetLength,
    Small,
    SmallCaps,
    Subparagraph,
    Subscript,
    Subsection,
    Subsubsection,
    Superscript,
    Texttt,
    Tiny,
    Underline,
    Whiledo,
)
from .library.document import Document
from .library.document_builtins import MakeTitle, NewPage, TableOfContents
from .library.environments import (
    BeginEnvironment,
    EndEnvironment,
    Enumerate,
    Environment,
    Flushleft,
    Item,
    Itemize,
    LongTable,
    MDFramed,
    Minipage,
    Picture,
    Put,
    Quote,
    TabularEnv,
    Titlepage,
    Verbatim,
)
from .library.figures import (
    SVG,
    Figure,
    HLine,
    IncludeGraphics,
    Row,
    Table,
    Tabular,
    tabular,
)
from .library.fontspec import NewFontFamily, SetMainFont, SetMonoFont, SetSansFont
from .library.glossaries import (
    Acronyms,
    AcronymEntry,
    Glossary,
    GlossaryEntry,
    MakeGlossaries,
    PrintGlossary,
    acr,
    acrfull,
    acrlong,
    gls,
    glspl,
)
from .library.glossary_style import (
    GlsAddKey,
    NewColumnType,
    NewGlossaryStyle,
    SetGlossaryStyle,
)
from .library.inclusion import Include, IncludeTeX
from .library.packages import RequirePackages
from .library.listings import (
    Bash,
    C,
    Cpp,
    Html,
    InlineCode,
    Java,
    JavaScript,
    Json,
    LaTeXListing,
    Listing,
    LstDefineStyle,
    LstSet,
    Php,
    Python,
    Rust,
    Shell,
    Sql,
    TypeScript,
)
from .library.markdown import Markdown
from .library.math import (
    Align,
    AlignStar,
    DisplayMath,
    Equation,
    EquationStar,
    Gather,
    InlineMath,
)
from .library.references import (
    Cite,
    ColorBox,
    FBox,
    Footnote,
    Label,
    PageRef,
    Ref,
    TextColor,
    cite,
)
from .model.base_model import Package, TeX
from .model.group import Group
from .model.raw import Raw

__version__ = "0.1.0"

__all__ = [
    "__version__",
    # Core types
    "TeX",
    "Package",
    "Raw",
    "Group",
    # Document structure
    "Document",
    "MakeTitle",
    "TableOfContents",
    "NewPage",
    # Generic command builders
    "Command",
    "NewCommand",
    "RenewCommand",
    "ProvideCommand",
    "DeclareRobustCommand",
    "NewLength",
    "SetLength",
    "NewCounter",
    "SetCounter",
    "CounterWithin",
    "CounterWithout",
    "AtBeginDocument",
    "AtEndDocument",
    "MakeAtLetter",
    "Hypersetup",
    "Crefname",
    "NewEnvironment",
    "GlobalDef",
    "BuiltinPackages",
    # Low-level primitives
    "Def",
    "Let",
    "NewToks",
    "AssignToks",
    "ImmediateWrite",
    "RegisterAssign",
    "Pretocmd",
    "Apptocmd",
    "AtBeginEnvironment",
    "AtEndEnvironment",
    "Whiledo",
    "IfFontExistsTF",
    "IfUndefined",
    "Ifnum",
    "Ifdefstring",
    "BeginAccSupp",
    # fontspec
    "NewFontFamily",
    "SetMainFont",
    "SetSansFont",
    "SetMonoFont",
    # Text formatting
    "Bold",
    "Italic",
    "Texttt",
    "Underline",
    "Emph",
    "SmallCaps",
    "Superscript",
    "Subscript",
    # Font sizes
    "Tiny",
    "Small",
    "Large",
    "LargeLarge",
    "LargeLargeLarge",
    "Huge",
    "HugeHuge",
    # Sections
    "Section",
    "Subsection",
    "Subsubsection",
    "Paragraph",
    "Subparagraph",
    # Links and utilities
    "Href",
    "Newline",
    "Relax",
    # Environments
    "Environment",
    "BeginEnvironment",
    "EndEnvironment",
    "Item",
    "Itemize",
    "Enumerate",
    "Quote",
    "Verbatim",
    "Minipage",
    "Put",
    "Picture",
    "MDFramed",
    "LongTable",
    "TabularEnv",
    "Flushleft",
    "Titlepage",
    # Math
    "InlineMath",
    "DisplayMath",
    "Equation",
    "EquationStar",
    "Align",
    "AlignStar",
    "Gather",
    # Figures & tables
    "IncludeGraphics",
    "SVG",
    "Figure",
    "Table",
    "Tabular",
    "tabular",
    "Row",
    "HLine",
    # References, citations, footnotes
    "Label",
    "Ref",
    "PageRef",
    "Cite",
    "cite",
    "Footnote",
    # Colors & boxes
    "TextColor",
    "ColorBox",
    "FBox",
    # File inclusion
    "Include",
    "IncludeTeX",
    "RequirePackages",
    # Glossaries
    "Glossary",
    "GlossaryEntry",
    "Acronyms",
    "AcronymEntry",
    "MakeGlossaries",
    "PrintGlossary",
    "gls",
    "glspl",
    "acr",
    "acrlong",
    "acrfull",
    # Glossary style helpers
    "NewColumnType",
    "NewGlossaryStyle",
    "SetGlossaryStyle",
    "GlsAddKey",
    # Listings
    "Listing",
    "LstSet",
    "LstDefineStyle",
    "InlineCode",
    "Python",
    "JavaScript",
    "TypeScript",
    "Cpp",
    "C",
    "Java",
    "Shell",
    "Bash",
    "Sql",
    "Html",
    "Php",
    "Rust",
    "Json",
    "LaTeXListing",
    # Markdown
    "Markdown",
    # biblatex
    "ExecuteBibliographyOptions",
    "DeclareFieldFormat",
    "DeclareCiteCommand",
    "DeclareNameAlias",
    "AddBibResource",
    "PrintBibliography",
]
