from enum import Enum

from pytex.model.package import DefinePackage, Package

__all__ = ["Packages"]

AMSMATH: Package = DefinePackage("amsmath")
AMSSYMB: Package = DefinePackage("amssymb")
AMSFONTS: Package = DefinePackage("amsfonts")
MATHTOOLS: Package = DefinePackage("mathtools")
HYPERREF: Package = DefinePackage("hyperref")
URL: Package = DefinePackage("url")
GRAPHICX: Package = DefinePackage("graphicx")
XCOLOR: Package = DefinePackage("xcolor")
GEOMETRY: Package = DefinePackage("geometry")
FONTENC: Package = DefinePackage("fontenc")
INPUTENC: Package = DefinePackage("inputenc")
BABEL: Package = DefinePackage("babel", options={"ngerman"})
MICROTYPE: Package = DefinePackage("microtype")
CSQUOTES: Package = DefinePackage("csquotes")
BOOKTABS: Package = DefinePackage("booktabs")
ARRAY: Package = DefinePackage("array")
TABULARX: Package = DefinePackage("tabularx")
LONGTABLE: Package = DefinePackage("longtable")
MULTIROW: Package = DefinePackage("multirow")
CAPTION: Package = DefinePackage("caption")
SUBCAPTION: Package = DefinePackage("subcaption")
FLOAT: Package = DefinePackage("float")
FANCYHDR: Package = DefinePackage("fancyhdr")
TITLESEC: Package = DefinePackage("titlesec")
ENUMITEM: Package = DefinePackage("enumitem")
LISTINGS: Package = DefinePackage("listings")
MINTED: Package = DefinePackage("minted")
TIKZ: Package = DefinePackage("tikz")
PGFPLOTS: Package = DefinePackage("pgfplots")
TCOLORBOX: Package = DefinePackage("tcolorbox")
SIUNITX: Package = DefinePackage("siunitx")
GLOSSARIES: Package = DefinePackage("glossaries", options={"acronym"})
SVG: Package = DefinePackage("svg")
SOUL: Package = DefinePackage("soul")
ULEM: Package = DefinePackage("ulem")
WRAPFIG: Package = DefinePackage("wrapfig")
PARSKIP: Package = DefinePackage("parskip")
SETSPACE: Package = DefinePackage("setspace")
TIKZ_LIB_ARROWS: Package = DefinePackage("tikz-arrows", after={TIKZ})
PGF: Package = DefinePackage("pgf")
LIPSUM: Package = DefinePackage("lipsum")
BLINDTEXT: Package = DefinePackage("blindtext")
TODONOTES: Package = DefinePackage("todonotes")
COMMENT: Package = DefinePackage("comment")
IFTHEN: Package = DefinePackage("ifthen")
ETOOLBOX: Package = DefinePackage("etoolbox")
XPARSE: Package = DefinePackage("xparse")
CALC: Package = DefinePackage("calc")
MAKEIDX: Package = DefinePackage("makeidx")
APPENDIX: Package = DefinePackage("appendix")
TITLING: Package = DefinePackage("titling")
LASTPAGE: Package = DefinePackage("lastpage")
CLEVEREF: Package = DefinePackage("cleveref", after={HYPERREF, AMSMATH})
VARIOREF: Package = DefinePackage("varioref")
FRAMED: Package = DefinePackage("framed")
# framemethod=tikz must be set at load time (preamble) for mdframed's rounded
# backgrounds; it cannot be switched on per-environment mid-document.
MDFRAMED: Package = DefinePackage("mdframed", options={("framemethod", "tikz")})
PDFPAGES: Package = DefinePackage("pdfpages")
FONTSPEC: Package = DefinePackage("fontspec")
UNICODE_MATH: Package = DefinePackage("unicode-math")
BIBLATEX: Package = DefinePackage("biblatex")
TOCLOFT: Package = DefinePackage("tocloft")
NOTOCCITE: Package = DefinePackage("notoccite")
NATBIB: Package = DefinePackage("natbib")
ACRONYM: Package = DefinePackage("acronym")
NOMENCL: Package = DefinePackage("nomencl")
ALGORITHM2E: Package = DefinePackage("algorithm2e")
ALGORITHMS: Package = DefinePackage("algorithms")
ALGORITHMICX: Package = DefinePackage("algorithmicx")
LSTLISTING: Package = LISTINGS  # alias
TBL_THEOREM: Package = DefinePackage("amsthm", after={AMSMATH})
AMSTHM: Package = TBL_THEOREM
THMTOOLS: Package = DefinePackage("thmtools")
ENUMERATE: Package = DefinePackage("enumerate")
PARALIST: Package = DefinePackage("paralist")
TYPEAREA: Package = DefinePackage("typearea")
SCRLAYER_SCRPAGE: Package = DefinePackage("scrlayer-scrpage")
KOMA_SCRIPT: Package = DefinePackage("koma-script")
ADJUSTBOX: Package = DefinePackage("adjustbox")
RAGGED2E: Package = DefinePackage("ragged2e")
NEEDSPACE: Package = DefinePackage("needspace")
PLACEINS: Package = DefinePackage("placeins")
FOOTMISC: Package = DefinePackage("footmisc")
ROTATING: Package = DefinePackage("rotating")
CHANGEPAGE: Package = DefinePackage("changepage")
EVERYPAGE: Package = DefinePackage("everypage")
EVERYSHI: Package = DefinePackage("everyshi")
TIKZ_LIB_POSITIONING: Package = DefinePackage("tikz-positioning", after={TIKZ})
TIKZPAGENODES: Package = DefinePackage("tikzpagenodes", after={TIKZ})
PGFFOR: Package = DefinePackage("pgffor")
ARRAYJOBX: Package = DefinePackage("arrayjobx")
BOPHOOK: Package = DefinePackage("bophook")
ENVIRON: Package = DefinePackage("environ")
EXPL3: Package = DefinePackage("expl3")
L3KEYS2E: Package = DefinePackage("l3keys2e")
PDFTEXCMDS: Package = DefinePackage("pdftexcmds")
XFP: Package = DefinePackage("xfp")
KEYVAL: Package = DefinePackage("keyval")
PIFONT: Package = DefinePackage("pifont")
FONTAWESOME: Package = DefinePackage("fontawesome")
FLOATROW: Package = DefinePackage("floatrow")
CHNGCNTR: Package = DefinePackage("chngcntr")
ACCSUPP: Package = DefinePackage("accsupp")
AFTERPAGE: Package = DefinePackage("afterpage")
ARYDSHLN: Package = DefinePackage("arydshln")
LMODERN: Package = DefinePackage("lmodern")
HYPHENAT: Package = DefinePackage("hyphenat")
FP: Package = DefinePackage("fp")


class Packages(Enum):
    AMSMATH = AMSMATH
    AMSSYMB = AMSSYMB
    AMSFONTS = AMSFONTS
    MATHTOOLS = MATHTOOLS
    HYPERREF = HYPERREF
    URL = URL
    GRAPHICX = GRAPHICX
    XCOLOR = XCOLOR
    GEOMETRY = GEOMETRY
    FONTENC = FONTENC
    INPUTENC = INPUTENC
    BABEL = BABEL
    MICROTYPE = MICROTYPE
    CSQUOTES = CSQUOTES
    BOOKTABS = BOOKTABS
    ARRAY = ARRAY
    TABULARX = TABULARX
    LONGTABLE = LONGTABLE
    MULTIROW = MULTIROW
    CAPTION = CAPTION
    SUBCAPTION = SUBCAPTION
    FLOAT = FLOAT
    FANCYHDR = FANCYHDR
    TITLESEC = TITLESEC
    ENUMITEM = ENUMITEM
    LISTINGS = LISTINGS
    MINTED = MINTED
    TIKZ = TIKZ
    PGFPLOTS = PGFPLOTS
    TCOLORBOX = TCOLORBOX
    SIUNITX = SIUNITX
    BIBLATEX = BIBLATEX
    GLOSSARIES = GLOSSARIES
    SVG = SVG
    SOUL = SOUL
    ULEM = ULEM
    WRAPFIG = WRAPFIG
    PARSKIP = PARSKIP
    SETSPACE = SETSPACE
    PGF = PGF
    LIPSUM = LIPSUM
    BLINDTEXT = BLINDTEXT
    TODONOTES = TODONOTES
    COMMENT = COMMENT
    IFTHEN = IFTHEN
    ETOOLBOX = ETOOLBOX
    XPARSE = XPARSE
    CALC = CALC
    MAKEIDX = MAKEIDX
    APPENDIX = APPENDIX
    TITLING = TITLING
    LASTPAGE = LASTPAGE
    CLEVEREF = CLEVEREF
    VARIOREF = VARIOREF
    FRAMED = FRAMED
    MDFRAMED = MDFRAMED
    PDFPAGES = PDFPAGES
    FONTSPEC = FONTSPEC
    UNICODE_MATH = UNICODE_MATH
    TOCLOFT = TOCLOFT
    NOTOCCITE = NOTOCCITE
    NATBIB = NATBIB
    ACRONYM = ACRONYM
    NOMENCL = NOMENCL
    ALGORITHM2E = ALGORITHM2E
    ALGORITHMS = ALGORITHMS
    ALGORITHMICX = ALGORITHMICX
    AMSTHM = AMSTHM
    THMTOOLS = THMTOOLS
    ENUMERATE = ENUMERATE
    PARALIST = PARALIST
    TYPEAREA = TYPEAREA
    SCRLAYER_SCRPAGE = SCRLAYER_SCRPAGE
    KOMA_SCRIPT = KOMA_SCRIPT
    ADJUSTBOX = ADJUSTBOX
    RAGGED2E = RAGGED2E
    NEEDSPACE = NEEDSPACE
    PLACEINS = PLACEINS
    FOOTMISC = FOOTMISC
    ROTATING = ROTATING
    CHANGEPAGE = CHANGEPAGE
    EVERYPAGE = EVERYPAGE
    EVERYSHI = EVERYSHI
    TIKZPAGENODES = TIKZPAGENODES
    PGFFOR = PGFFOR
    ARRAYJOBX = ARRAYJOBX
    BOPHOOK = BOPHOOK
    ENVIRON = ENVIRON
    EXPL3 = EXPL3
    L3KEYS2E = L3KEYS2E
    PDFTEXCMDS = PDFTEXCMDS
    XFP = XFP
    KEYVAL = KEYVAL
    PIFONT = PIFONT
    FONTAWESOME = FONTAWESOME
    FLOATROW = FLOATROW
    CHNGCNTR = CHNGCNTR
    ACCSUPP = ACCSUPP
    AFTERPAGE = AFTERPAGE
    ARYDSHLN = ARYDSHLN
    LMODERN = LMODERN
    HYPHENAT = HYPHENAT
    FP = FP
