from enum import Enum

from pytex.model.package import DefinePackage, Package

AMSMATH: Package = DefinePackage("amsmath")
AMSSYMB: Package = DefinePackage("amssymb")
AMSFONTS: Package = DefinePackage("amsfonts")
MATHTOOLS: Package = DefinePackage("mathtools")
HYPERREF: Package = DefinePackage("hyperref")
URL: Package = DefinePackage("url")
GRAPHICX: Package = DefinePackage("graphicx")
XCOLOR: Package = DefinePackage("xcolor")
GEOMETRY: Package = DefinePackage("geometry")
FONTENC: Package = DefinePackage("fontenc")
INPUTENC: Package = DefinePackage("inputenc")
BABEL: Package = DefinePackage("babel")
MICROTYPE: Package = DefinePackage("microtype")
CSQUOTES: Package = DefinePackage("csquotes")
BOOKTABS: Package = DefinePackage("booktabs")
ARRAY: Package = DefinePackage("array")
TABULARX: Package = DefinePackage("tabularx")
LONGTABLE: Package = DefinePackage("longtable")
MULTIROW: Package = DefinePackage("multirow")
CAPTION: Package = DefinePackage("caption")
SUBCAPTION: Package = DefinePackage("subcaption")
FLOAT: Package = DefinePackage("float")
FANCYHDR: Package = DefinePackage("fancyhdr")
TITLESEC: Package = DefinePackage("titlesec")
ENUMITEM: Package = DefinePackage("enumitem")
LISTINGS: Package = DefinePackage("listings")
MINTED: Package = DefinePackage("minted")
TIKZ: Package = DefinePackage("tikz")
PGFPLOTS: Package = DefinePackage("pgfplots")
TCOLORBOX: Package = DefinePackage("tcolorbox")
SIUNITX: Package = DefinePackage("siunitx")
BIBLATEX: Package = DefinePackage("biblatex")
GLOSSARIES: Package = DefinePackage("glossaries")
SVG: Package = DefinePackage("svg")
SOUL: Package = DefinePackage("soul")
ULEM: Package = DefinePackage("ulem")
WRAPFIG: Package = DefinePackage("wrapfig")
PARSKIP: Package = DefinePackage("parskip")
SETSPACE: Package = DefinePackage("setspace")


class Packages(Enum):
    AMSMATH = AMSMATH
    AMSSYMB = AMSSYMB
    AMSFONTS = AMSFONTS
    MATHTOOLS = MATHTOOLS
    HYPERREF = HYPERREF
    URL = URL
    GRAPHICX = GRAPHICX
    XCOLOR = XCOLOR
    GEOMETRY = GEOMETRY
    FONTENC = FONTENC
    INPUTENC = INPUTENC
    BABEL = BABEL
    MICROTYPE = MICROTYPE
    CSQUOTES = CSQUOTES
    BOOKTABS = BOOKTABS
    ARRAY = ARRAY
    TABULARX = TABULARX
    LONGTABLE = LONGTABLE
    MULTIROW = MULTIROW
    CAPTION = CAPTION
    SUBCAPTION = SUBCAPTION
    FLOAT = FLOAT
    FANCYHDR = FANCYHDR
    TITLESEC = TITLESEC
    ENUMITEM = ENUMITEM
    LISTINGS = LISTINGS
    MINTED = MINTED
    TIKZ = TIKZ
    PGFPLOTS = PGFPLOTS
    TCOLORBOX = TCOLORBOX
    SIUNITX = SIUNITX
    BIBLATEX = BIBLATEX
    GLOSSARIES = GLOSSARIES
    SVG = SVG
    SOUL = SOUL
    ULEM = ULEM
    WRAPFIG = WRAPFIG
    PARSKIP = PARSKIP
    SETSPACE = SETSPACE
